


# --- JPA ---
spring.jpa.hibernate.ddl-auto=validate
spring.datasource.hikari.maximum-pool-size=${DB_POOL_SIZE:1}
spring.datasource.hikari.minimum-idle=${DB_MIN_IDLE:0}

# --- Swagger ---
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

# --- Logs ---
logging.level.root=INFO
logging.level.edu.eci.patricia=DEBUG
