
spring.datasource.hikari.maximum-pool-size=3

# --- JPA: create-drop mientras no hay migraciones Flyway ---
spring.jpa.hibernate.ddl-auto=create-drop

# --- Swagger habilitado en QA para pruebas ---
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

# --- Logs ---
logging.level.root=INFO
logging.level.com.suport=DEBUG
