spring.application.name=m09-eventos-universitarios

# MongoDB
# URI de conexión a MongoDB local.
# En producción reemplazar por variable de entorno: ${MONGODB_URI}
spring.data.mongodb.uri=mongodb://localhost:27017/patricia_eventos
spring.data.mongodb.database=patricia_eventos

# Logging
logging.level.root=WARN
logging.level.edu.eci.patricia=DEBUG
logging.pattern.console=%d{HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Swagger / OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha

# Servidor
server.port=8080