# --- JPA ---
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.datasource.hikari.maximum-pool-size=5

# --- Swagger ---
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

# --- Logs ---
logging.level.root=WARN
logging.level.com.suport=INFO
