


# --- JPA ---
spring.jpa.hibernate.ddl-auto=validate
spring.datasource.hikari.maximum-pool-size=3

# --- Swagger ---
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

# --- Logs ---
logging.level.root=INFO
logging.level.com.suport=DEBUG
